version: '3.3'

services:
  tg:
    container_name: tg
    build: ./back
    volumes:
      - ./:/bot_catalog
    command: python3 back/bot/main.py
    env_file:
      - ".env"

  api:
    container_name: api
    build: ./back
    command: python3 back/api/main.py
    volumes:
      - ./:/bot_catalog
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      - db
      - tg
    env_file:
      - ".env"

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - print_db:/var/lib/postgresql/data


volumes:
  print_db: